### ISSUE TITLE
Wow, ignorant author

### ISSUE THREAD

**Issue by AWateround** [spatie/ssl-certificate#108]
Just tried to make it work since 1 hour and just saw that it for Laravel only.
Idiot author, you SHOULD WRITE IN THE DESCRIPTION, NOT IN YOUR WEBSITE.

No fuckin info on GitHub page.

Dumb idiot.

SMHU.

**Comment by freekmurze** [comment]
This package is not Laravel only. 

Please refrain from using offensive language on our issue tracker.

**Comment by zoransa** [comment]
Freek Van der Herten is one of the kindest and the most generous opensource contributors on the world.

**Comment by MrJmpl3** [comment]
@AWateround if you don't know programming, please first learn before to create a issue in Github

**Comment by keevitaja** [comment]
I confirm it is not working. Tried to install in on my brand new VIC-20. Nothing! It just will NOT install.

**Comment by ConsoleTVs** [comment]
Your github profile is ignorant.

**Comment by drewroberts** [comment]
I got @freekmurze's back. Let's step this outside into the back alley...

🤕

**Comment by mtownsend5512** [comment]
Go produce your own superior package then.

**Comment by sebsel** [comment]
@keevitaja wrote:
> I confirm it is not working. Tried to install in on my brand new VIC-20. Nothing! It just will NOT install.

Maybe good to call out that this was sarcasm / a joke. I just tried this package in an empty non-Laravel project and as usual with Spatie: it works like a charm :)

**Comment by Jamesking56** [comment]
They only joined July 9th, maybe just to create these sorts of issues?

**Comment by euperia** [comment]
I don't think is fair to ridicule the OP; he does have a point in saying that the README doesn't state that the package will only work on Laravel.  Not everyone knows that Spatie make Laravel packages, especially if you're new to the framework or to PHP.

Totally fair to point out the aggressive tone and abusive language though.

**Comment by Jamesking56** [comment]
@euperia This package doesn't _just_ work on Laravel, its built for any PHP project not just Laravel.

**Comment by ccmiller2018** [comment]
<sarcasm> can confirm this package is fully working on my ZX Spectrum 48k running php version 0.0.1a </sarcasm>

more seriously, i've used this outside laravel myself.  chill!

**Comment by Stokoe0990** [comment]
I'm actually with @euperia on this one.

I kind of feel like there should be a paragraph under the name of the package in the readme that explains this package is just a PHP package that is framework-agnostic.

**Comment by euperia** [comment]
> @euperia This package doesn't _just_ work on Laravel, its built for any PHP project not just Laravel.

My bad.  I got confused.

**Comment by Jamesking56** [comment]
> > I'm actually with @euperia on this one.
> > I kind of feel like there should be a paragraph under the name of the package in the readme that explains this package is just a PHP package that is framework-agnostic.
> 
> Why?  It's pretty clear that it's framework agnostic. Adding unnecessary text to the readme makes it worse.

I agree with this, does this mean every single PHP package on GitHub needs to say that they are framework-agnostic?

If it doesn't mention Laravel, then it not Laravel-specific.

**Comment by Gummibeer** [comment]
Should it also be noted that it's PHP and not JS, GO or any language? Or that it's only compatible with PHP >7.2?
**No**, because there is a [composer.json](https://github.com/spatie/ssl-certificate/blob/master/composer.json) which clearly describes everything important about the packages requirements and compatibilities.

I clearly go with @freekmurze - just because it's Open Source and no one has to pay money to use it or to get support it doesn't mean that the issues should be used like a facebook hate post.
Most of us do this in addition to a full-time job in our freetime or have a generous agreement with our boss to spend some work time for it as a compensation for the saved time by using these packages.
And I would say that all @spatie and also most other open source contributors do this work because they love what they do and feel good to give something to the community. But it's unacceptable to not appreciate this time/work and insult someone or also open issues like "it does not work". We are also not a dog which is happy by getting a bone thrown infront of him.

We are happy and feel great for **every** single nice word we get. And if it's a single *Thank you*.
We are happy to help someone who does his part to solve the issue and also are happy about every reported bug.
But it costs a lot of emotional power and nerves to keep cool in issues like this. Or ask the thousandth time to get a more detailed description, stack trace or any other details.

Why I write this much here? Because sometimes things have to be said - even if most of the readers already know this and I believe, with sadness, that nothing will change in the issue section.
But sometimes it feels like users think that the work that's done for open source get's paid by imagination and we have 48h days and eat love (if we get some), air and bugs. Or they have some kind of royal platin premium support plan because there isn't anything that states something different.

For those who are interested in how much time it costs to **just** contribute/collaborate to ~5-10 open source packages - feel free to follow up.

<details>
<summary>toggle me</summary>

> Seven days a week my day starts by checking my github notifications right before morning bath session and my first coffee. This is just a check what happened during the night (different timezones) and if something important occurred. *~5min*

After this it splits workdays and weekend/holidays.

> During weekends and holidays I try to do nearly nothing except there is an issue I'm personally interested in and/or which is kind of important. *~0-15min*

> During normal workdays I try to answer some issues during getting my coffee, lunch and waiting for builds, deployments and so on. *~5-60min*

> After my normal work I try to find some time to fix bugs, write new features and do other coding tasks or answer issues which need more investigation or a quick unittest to demonstrate that/how it works or find out that it's really a bug. *~15-120min*

> For new/big features/packages I also need some time to discuss with the other collaborators via chat/email, concept features, write pseudo code to have a discussion base and so on. *~0-60min*

So all in all I spend around 2.25 - 17 hours a week. In average it's more to the top value like 10-15h/week
```
(7 * 5min) + (2 * 0min) + (5 * 5min) + (5 * 15min) + 0min = 2.25 hours
(7 * 5min) + (2 * 15min) + (5 * 60min) + (5 * 120min) + 60min = 17 hours
```

And I 100% agree that I do this without getting forced to do so! So no need to say *You don't have to do it* - like on weekends I also take my own freetime.

</details>

But one request:
If anyone takes the time to answer your issue, review your PR or even fix a bug or write new features. **Be kind and show some respect/love!** It doesn't cost anything except some more keystrokes but makes a **huge** difference for the other one. Like in most scenarios in your life, just imagine how you would feel as the other one!?

**Comment by ManojKiranA** [comment]
@AWateround if you don't know how to use it in non laravel application just ask for help.

**Comment by zoransa** [comment]
https://github.com/spatie/ssl-certificate/blob/master/composer.json#L19

"require": {
        "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.8.*",
        "laravel/tinker": "^1.0"
    }

if your configuration does not meet this requirement why are you whining?
