### ISSUE TITLE
SSL Download error: Unknown

### ISSUE THREAD

**Issue by sumityadav** [spatie/ssl-certificate#17]
I am using `spatie/laravel-uptime-monitor` and one of the domain that I added gives me the following error message:

Could not download certificate of https://www.<domain-name>.com because: Unknown.

![2017-03-18_2157](https://cloud.githubusercontent.com/assets/169143/24074053/a49b687c-0c27-11e7-9a2e-ae9e85640dd4.png)

Do you have any feedback? I am sure that the domain is actually valid and the SSL certificates are valid too.

**Comment by mallardduck** [comment]
Can you confirm that the domain you're working with has a valid SSL? Have you tested the SSL with another tool?

Here's a few tools you can try:
https://www.sslshopper.com/ssl-checker.html - Independent tool, unsure of the sources
https://sslcheck.liquidweb.com/ - A tool I created which uses a library originally inspired by [spatie/ssl-certificate](https://github.com/spatie/ssl-certificate)

If the SSL is definitely 100% working, valid, properly installed then I'm gonna guess the issue isn't related to this package specifically. My bet is that the issue is coming from the original `laravel-uptime-monitor` package rather than the SSL one here.

**Comment by sumityadav** [comment]
Yes, I verified both the links and both sites validate the certificate without issue.

![sslcheck](https://cloud.githubusercontent.com/assets/169143/24891267/51390414-1e92-11e7-96f7-bcb48446b26d.png)

**Comment by sumityadav** [comment]
I installed the package as standalone from composer trying to see if the issue is from this package or `spatie/laravel-uptime-monitor`, to my surprise, for the same domain I was able to download the ssl certificate and validate it.

I think it is good to close the issue on this package and bump up the issue on the `laravel-uptime-monitor`
